dabao1955/kernel_build_action

action.yml

action.yml: Fix typo on folder name

---

action.yml

https://github.com/jun10r4lm31d4/build_kernel/actions/runs/10310095408/job/28541130858#step:3:1235

Fix build error with ksu: true

---

action.yml

https://github.com/jun10r4lm31d4/op8/actions/runs/10326133254/job/28589086127#step:3:974

Fix ndk download

---

action.yml

fix CROSS_COMPILE_ARM32,close #27

---

action.yml

https://github.com/frstprjkt/kernel_xiaomi_sm6115/actions/runs/12030625992/job/33538419893#step:2:562 (fixed by "[actions: set android-version input required to false](https://github.com/frstprjkt/kernel_build_action/commit/de5e9c05586598a498a8e5a676c8b9b591ce949c)")
https://github.com/frstprjkt/kernel_xiaomi_sm6115/actions/runs/12030433993/job/33537831958#step:2:596 (fixed by "[actions: fix mkdir error when using 3rd clang](https://github.com/frstprjkt/kernel_build_action/commit/4725e9a9f5872a77f5d1564c6275de515792df4e)")

fix download clang issues

---

README.md
action.yml
tests/README.md

Reverts dabao1955/kernel_build_action#51

Revert "Add basic third patry GCC support"

---

action.yml

Simplify the code

---

action.yml

Merge aosp gcc and 3rd-gcc code

---

action.yml

actions: Guard GCC stuff

---

action.yml
kernelsu/patch.sh

Fix umount code insertion position

---

kernelsu/patch.sh

Fix potential errors in the variable

---

kernelsu/patch.sh

Fix patch application feedback

---

action.yml

Simplify the code to fix the LXC patch path errora

---

kernelsu/patch.sh

Add inode.c patch

---

action.yml

Potential Errors in Patch Fixes

---

kernelsu/patch.sh

Fix Potential Errors while patching in kernelsu step

---

action.yml

- switch ccache to masquerade mode to fix errors (e.g. unterminated quoted string, invalid switch, etc..)
- inputs.ccache logic into a single logic block.
- refactor COMMAND variable generation to accomodate the two changes
above.

actions: switch ccache run mode to use masquerade 

---

kernelsu/patch.sh

Avoid specifying the path multiple times

---

action.yml

Add support to extract xz file format

actions: Add support to extract xz tarball

---

action.yml

install pigz
some users may use pigz for gzip to speed up builds

actions: install parallel implementation of gzip

---

kernelsu/patch.sh

Guard fs/namespace.c on KernelSU patching
Some kernel source already have this patch, so not need to patch it again.

patch: Guard fs/namespace.c patch

---

action.yml

code improvement

---

action.yml

actions: fix typo

---

action.yml

Fix the invalid command for aria2c

---

kernelsu/patch.sh

Add the hooks.c patch from JackA1ltman

---

kernelsu/patch.sh

Add ksu_sid check

---

kernelsu/patch.sh

Use a regular expression to avoid duplicate matching of the two strings

---

action.yml

fix building on custom clang

---

action.yml

- Follow AOSP README.[1]
[1] - https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/70a12c4fe88940ab2b0e6d763492dffa2f07e15a

actions: Update AOSP clang default branch

---

action.yml

actions: fix(release): Fix Anykernel 3 can not flash while releaseing
